"""Los seis roles de la tabla K del documento de reglas, como datos.

Es la única definición: la migración siembra la tabla `roles` desde aquí y la siembra en arranque la repone
si falta. Las secciones son las que el frontend muestra en el menú; las acciones, lo que la API deja firmar.
"""

ROLES_BASE: list[dict] = [
    {
        "id": "auditor_clinico",
        "orden": 1,
        "nombre": "Auditor clínico",
        "descripcion": "Resuelve la cola de revisión humana; puede bajar una prioridad con justificación escrita.",
        "ve": "Documento completo",
        "puede": "Aprobar, corregir, bajar prioridad con justificación",
        "secciones": ["inicio", "documentos", "revision", "alertas", "pacientes", "entregas"],
        "acciones": ["resolver_revision", "acusar_alerta", "editar_paciente"],
        "tipos_documento": [],  # RN-J9: solo el rol de auditoría ve todo
        "ve_documentos": True,
        "ruta_inicial": "/revision",
        "modo_discreto": False,
        "alto_contraste": False,
        "pantalla_compartida": False,
    },
    {
        "id": "quimico_farmaceutico",
        "orden": 2,
        "nombre": "Químico farmacéutico",
        "descripcion": "Verifica recetas; las de alto riesgo y control especial llevan doble verificación.",
        "ve": "Recetas",
        "puede": "Doble verificación de alto riesgo y control especial",
        "secciones": ["inicio", "farmacia", "documentos"],
        "acciones": ["verificar_receta"],
        "tipos_documento": ["Receta Médica"],
        "ve_documentos": True,
        "ruta_inicial": "/farmacia",
        "modo_discreto": False,
        "alto_contraste": False,
        "pantalla_compartida": False,
    },
    {
        "id": "auditor_autorizaciones",
        "orden": 3,
        "nombre": "Auditor de autorizaciones",
        "descripcion": "Aprueba o devuelve órdenes ambulatorias con su documentación mínima.",
        "ve": "Orden y justificación mínima",
        "puede": "Aprobar o devolver órdenes",
        "secciones": ["inicio", "autorizaciones", "documentos"],
        "acciones": ["resolver_autorizacion"],
        "tipos_documento": ["Orden de Procedimiento"],
        "ve_documentos": True,
        "ruta_inicial": "/autorizaciones",
        "modo_discreto": False,
        "alto_contraste": False,
        "pantalla_compartida": False,
    },
    {
        "id": "jefe_urgencias",
        "orden": 4,
        "nombre": "Jefe de urgencias",
        "descripcion": "Da acuse a las alertas críticas y las reasigna.",
        "ve": "Alertas críticas escaladas",
        "puede": "Dar acuse, reasignar",
        "secciones": ["inicio", "alertas", "documentos"],
        "acciones": ["acusar_alerta", "resolver_revision"],
        "tipos_documento": [],
        "ve_documentos": True,
        "ruta_inicial": "/alertas",
        "modo_discreto": True,
        "alto_contraste": True,
        "pantalla_compartida": True,
    },
    {
        "id": "gestor",
        "orden": 5,
        "nombre": "Gestor de la clínica",
        "descripcion": "Configuración dentro de límites y métricas. No revisa documentos.",
        "ve": "Configuración y métricas",
        "puede": "Cambiar configuración dentro de límites",
        "secciones": ["inicio", "metricas", "configuracion"],
        "acciones": ["configurar"],
        "tipos_documento": [],
        "ve_documentos": False,
        "ruta_inicial": "/metricas",
        "modo_discreto": True,
        "alto_contraste": False,
        "pantalla_compartida": False,
    },
    {
        "id": "administrador",
        "orden": 6,
        "nombre": "Administrador del sistema",
        "descripcion": "Usuarios y pack de país. Nada clínico.",
        "ve": "Usuarios y pack de país",
        "puede": "Nada clínico",
        "secciones": ["inicio", "administracion"],
        "acciones": ["administrar"],
        "tipos_documento": [],
        "ve_documentos": False,
        "ruta_inicial": "/administracion",
        "modo_discreto": True,
        "alto_contraste": False,
        "pantalla_compartida": False,
    },
]
