"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 01:00:34.151655
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('documento_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('hash_contenido', sa.String(length=64), nullable=False),
    sa.Column('estado', sa.String(length=32), nullable=False),
    sa.Column('canal_origen', sa.String(length=32), nullable=False),
    sa.Column('pais_origen', sa.String(length=2), nullable=False),
    sa.Column('tipo_contenido', sa.String(length=16), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=True),
    sa.Column('formato', sa.String(length=8), nullable=True),
    sa.Column('num_paginas', sa.Integer(), nullable=False),
    sa.Column('paginas_json', sa.JSON(), nullable=True),
    sa.Column('cobertura_paciente', sa.String(length=32), nullable=True),
    sa.Column('tamano_bytes', sa.Integer(), nullable=False),
    sa.Column('status_backup', sa.String(length=16), nullable=False),
    sa.Column('ruta_storage', sa.String(length=512), nullable=True),
    sa.Column('posible_duplicado_de', sa.String(length=128), nullable=True),
    sa.Column('codigo_error', sa.String(length=64), nullable=True),
    sa.Column('resultado_json', sa.JSON(), nullable=True),
    sa.Column('texto_seudonimizado', sa.Text(), nullable=True),
    sa.Column('mapa_reidentificacion', sa.JSON(), nullable=True),
    sa.Column('propuesta_json', sa.JSON(), nullable=True),
    sa.Column('nivel_prioridad', sa.String(length=16), nullable=True),
    sa.Column('entregas_json', sa.JSON(), nullable=True),
    sa.Column('modelo_llm', sa.String(length=64), nullable=True),
    sa.Column('version_prompt', sa.String(length=32), nullable=True),
    sa.Column('tokens_entrada', sa.Integer(), nullable=False),
    sa.Column('tokens_salida', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_id', 'version', name='uq_documento_version')
    )
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_documento_id'), ['documento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_hash_contenido'), ['hash_contenido'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_nivel_prioridad'), ['nivel_prioridad'], unique=False)

    op.create_table('alertas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('documento_pk', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.String(length=128), nullable=False),
    sa.Column('nivel', sa.String(length=16), nullable=False),
    sa.Column('canal', sa.String(length=16), nullable=False),
    sa.Column('destinatario', sa.String(length=128), nullable=False),
    sa.Column('mensaje', sa.String(length=512), nullable=False),
    sa.Column('enlace', sa.String(length=512), nullable=True),
    sa.Column('estado_acuse', sa.String(length=16), nullable=False),
    sa.Column('emitida_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acusado_por', sa.String(length=128), nullable=True),
    sa.Column('acusado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalamientos', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['documento_pk'], ['documentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_pk', 'nivel', name='uq_alerta_documento_nivel')
    )
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alertas_documento_id'), ['documento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertas_documento_pk'), ['documento_pk'], unique=False)

    op.create_table('correcciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('documento_pk', sa.Integer(), nullable=False),
    sa.Column('campo', sa.String(length=256), nullable=False),
    sa.Column('extraido', sa.JSON(), nullable=True),
    sa.Column('corregido', sa.JSON(), nullable=True),
    sa.Column('usuario', sa.String(length=128), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['documento_pk'], ['documentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correcciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correcciones_documento_pk'), ['documento_pk'], unique=False)

    op.create_table('transiciones_estado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('documento_pk', sa.Integer(), nullable=False),
    sa.Column('de_estado', sa.String(length=32), nullable=True),
    sa.Column('a_estado', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('motivo', sa.String(length=512), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['documento_pk'], ['documentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transiciones_estado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transiciones_estado_documento_pk'), ['documento_pk'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transiciones_estado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transiciones_estado_documento_pk'))

    op.drop_table('transiciones_estado')
    with op.batch_alter_table('correcciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correcciones_documento_pk'))

    op.drop_table('correcciones')
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alertas_documento_pk'))
        batch_op.drop_index(batch_op.f('ix_alertas_documento_id'))

    op.drop_table('alertas')
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_nivel_prioridad'))
        batch_op.drop_index(batch_op.f('ix_documentos_hash_contenido'))
        batch_op.drop_index(batch_op.f('ix_documentos_documento_id'))

    op.drop_table('documentos')
    # ### end Alembic commands ###
