"""verificaciones de farmacia y autorizacion

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 02:36:46.450696
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verificaciones_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('autorizacion_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_column('autorizacion_json')
        batch_op.drop_column('verificaciones_json')

    # ### end Alembic commands ###
